package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/workspace/8-2-build-solaris-amd64/jdk8u112/7884/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, September 22, 2016 10:36:53 PM UTC
*/

public interface ServerManager extends ServerManagerOperations, com.sun.corba.se.spi.activation.Activator, com.sun.corba.se.spi.activation.Locator
{
} // interface ServerManager
